### ISSUE TITLE
The link to the proposal has stopped working

### ISSUE THREAD

**Issue by natashenka** [leobalter/proposal-setmap-offrom#12]
https://leobalter.github.io/proposal-setmap-offrom/ does not work for me

**Comment by ljharb** [comment]
Changed to https://tc39.github.io/proposal-setmap-offrom/

**Comment by natashenka** [comment]
Thanks!

**Comment by BridgeAR** [comment]
This should probably be closed?

**Comment by ExE-Boss** [comment]
It’s still incorrect in the repository header just under the tabs.

**Comment by bakkot** [comment]
It looks correct to me, so I'm closing this, but please let me know if I'm missing something.

**Comment by ExE-Boss** [comment]
@bakkot I mean the URL on this page:

[![Screenshot_2019-10-22 – TC39 – proposal‑setmap‑offrom – GitHub URL](https://user-images.githubusercontent.com/3889017/67258489-2e8df000-f491-11e9-9248-65128e3d38ae.png)](https://github.com/tc39/proposal-setmap-offrom)

It should now probably be: https://tc39.es/proposal-setmap-offrom/, to match the other proposals.

**Comment by bakkot** [comment]
Oh, sure. Fixed.
