### ISSUE TITLE
Map.from === WeakMap.from, etc?

### ISSUE THREAD

**Issue by zloirock** [leobalter/proposal-setmap-offrom#13]
Methods on all collection constructors have the same logic. Should those functions be the same object on all constructors?

**Comment by ljharb** [comment]
That’d be great.

**Comment by michaelficarra** [comment]
Let's not. I would prefer #16, and even without that, I wouldn't want to lock us in to the functions being reference identical.

**Comment by zloirock** [comment]
@michaelficarra binding looks prettily, but, as I wrote, #16 is not acceptable [by the current language design](https://github.com/tc39/ecma262/issues/544), so the current solution is better than nothing.

**Comment by ljharb** [comment]
Without #16, why wouldn't you want to lock us in to that? What semantics would you expect to change in one function but not the other?

**Comment by bakkot** [comment]
@ljharb Why _would_ you want to lock us into it? What benefit is there in doing so?

**Comment by zloirock** [comment]
The spec minimizes the number of identical objects / methods. For example, `Set.prototype.keys` === `Set.prototype.values` === `Set.prototype[@@iterator]`. Here the same situation. In addition, it finally approves these methods as generics, so that means that because of duck-typing they will work with similar objects from userland (for example, something `Map`-like, but what can't be inherited from `Map`).

**Comment by zloirock** [comment]
Maybe you will say any arguments against it? I can't understand your position - just aggressive defense of #16 (which, sure, if it will be accepted, will be in priority) or something else?

**Comment by bakkot** [comment]
I don't think it makes sense to try to do that minimization across different classes unless there is some particular reason to do so.

The argument against it is as @michaelficarra gave above: it prevents us from ever changing the behavior of one without changing the behavior of all the others.

**Comment by zloirock** [comment]
Makes sense or not - it's a practice from ES spec. They have the same behavior, it's the main argument of this issue, so changing of the behavior is unrelated.

**Comment by michaelficarra** [comment]
@zloirock There's a difference between *necessarily* having the same behaviour (Set#keys / Set#values) and incidentally having the same behaviour.

**Comment by zloirock** [comment]
@michaelficarra so, in which cases it's possible? Please, an example.

**Comment by zloirock** [comment]
It seems it can be closed because of https://github.com/tc39/proposal-setmap-offrom/issues/16#issuecomment-1843346541.
