### ISSUE TITLE
Problems with CollectionCreate

### ISSUE THREAD

**Issue by allenwb** [leobalter/proposal-setmap-offrom#2]
The signature of CollectionCreate (and the assert in step 1) says that the second parameter is an iterable object but the defintions of Map.of and Set.of pass a List as the second argument.  A List is not an obect and hence not an Iterable.

I suggest that you define the second parameter to be an Iterator and pass a [ListIterator](https://tc39.github.io/ecma262/#sec-createlistiterator) from Map.of and Set.of as the argument to CollectionCreate

Also, step 3 references _items_ which isn't defined

**Comment by leobalter** [comment]
That's right! I used the ListIterator and that was a good approach for it.

 72aa0d7 is addressing it.
