### ISSUE TITLE
CreateCollectionFrom: arity conflict calling add method

### ISSUE THREAD

**Issue by allenwb** [leobalter/proposal-setmap-offrom#5]
The value of _add__ is either "add" or "set" and is called as:
Call(_add_, _targetObj_, « _mappedValue_ » )(

but, the Map `set` method requires two arguments while the and the Set `add` method only takes one.  You don't take that into account.

**Comment by leobalter** [comment]
The new abstraction creates a temporary array to parse the items through the mapping function and calls the constructor using it. The adder method is not necessary anymore in this case.

Ref https://leobalter.github.io/proposal-setmap-offrom/#sec-collectioncreatefrom%20aoid=
