### ISSUE TITLE
Optionalness of arguments can't be chained

### ISSUE THREAD

**Issue by allenwb** [leobalter/proposal-setmap-offrom#6]
Map.from (etc) takes two optional arguments, but passes the (possibly defaulted) values of the parameters unconditionally to ColletionCreateFrom.  Once that happens, they are no longer optional arguments to CollectionCreateFrom but explicitly passed arguments. 

You need to handle this similarly to how it is handled in [Array.from](https://tc39.github.io/ecma262/#sec-array.from)

**Comment by leobalter** [comment]
They are still optional in the concept they are ok if their values are not provided or just undefined.

In anyway, there's no operation calling ColletionCreateFrom with a different size of arguments, so we don't need to specify those are optional args.
